version: 2.1

orbs:
  node: circleci/node@1.1
  jira: circleci/jira@1.3.1

jobs:
  build:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run:
          name: test
          command: yarn test
      - run:
          name: bundlesize
          command: yarn size
      - run:
          name: build
          command: yarn build

workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify