version: 2.1

orbs:
  node: circleci/node@1.1
  codecov: codecov/codecov@1.2.3

jobs:
  build:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
      - run:
          name: test
          command: yarn coverage
      - store_artifacts:
          path: ./coverage
      - run:
          name: codecov
          command: codecov/upload
          environment:
            file: ./coverage/clover.xml
      - run:
          name: build
          command: yarn build
      - store_artifacts:
          path: build
      - run:
          name: bundlesize
          command: yarn size
