version: 2.1
orbs:
  node: circleci/node@1.1
  jira: circleci/jira@1.3.1
jobs:
  build:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify