version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
  build:
    executor:
      name: node/default
      tag: '14.16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
      - run:
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
      - store_artifacts:
          path: build
      - run:
          name: bundlesize
          command: yarn size
      - run:
          name: install lighthouse-cli
          command: sudo npm install -g @lhci/cli@0.7.x
      - run:
          name: lighthouse
          command: lhci autorun
